### ISSUE TITLE
Problems getting LDAP authentication working

### ISSUE THREAD

**Issue by sscotter** [ctxis/crackerjack#13]
Hi,

I've run into two problems while configuring LDAP authentication.

1) I'm unable to get SSL to work even though I know my active directory supports it. No errors are generated in syslog, just fails with a 500 error.

2) If I specify the domain CORRECTLY I get a 500 error and the following error in syslog...

```
Oct 14 17:18:11 atlas gunicorn[790]: [2021-10-14 17:18:11,515] ERROR in app: Exception on /auth/login [POST]
Oct 14 17:18:11 atlas gunicorn[790]: Traceback (most recent call last):
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Oct 14 17:18:11 atlas gunicorn[790]:     response = self.full_dispatch_request()
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Oct 14 17:18:11 atlas gunicorn[790]:     rv = self.handle_user_exception(e)
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Oct 14 17:18:11 atlas gunicorn[790]:     reraise(exc_type, exc_value, tb)
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Oct 14 17:18:11 atlas gunicorn[790]:     raise value
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Oct 14 17:18:11 atlas gunicorn[790]:     rv = self.dispatch_request()
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Oct 14 17:18:11 atlas gunicorn[790]:     return self.view_functions[rule.endpoint](**req.view_args)
Oct 14 17:18:11 atlas gunicorn[790]:   File "/opt/crackerjack/app/controllers/auth.py", line 68, in login_process
Oct 14 17:18:11 atlas gunicorn[790]:     user = users.get_ldap_user(ldap_user['username'])
Oct 14 17:18:11 atlas gunicorn[790]: TypeError: 'bool' object is not subscriptable
``` 

However, if I set domain intentionally INCORRECTLY then LDAP authentication works. Very strange!

Cheers

Steve

**Comment by sadreck** [comment]
I've added an option to select between "Simple" and "NTLM" under the settings.

I'll close the issue now, but if something isn't working feel free to open it again.
