### ISSUE TITLE
Allow selecting of GPUs

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#14]
Hashcat tends to be quite greedy on GPU RAM. It would be nice if we could parallelise some of our cracks by allow only certain GPUs to be selected, so we can have, say urgent and heavy jobs on the 3080s and less urgent on the 2080s.

This can be defined using the -d/-D flag to hashcat (where the ids can be found from hashcat -I). Ideally I'd like to have profiles that I can set up as the administrator and let the users choose.

A quick workaround may by to allow custom flags to be applied to the hashcat command option, though this would need careful checking to prevent command injection.

**Comment by sadreck** [comment]
That's a great idea and I like the profile approach.

Thanks for the recommendation, I'll see what I can do.

**Comment by sadreck** [comment]
I pushed this feature to the `develop` branch - if you have time give it a go and let me know if there are any issues. Profile creation is in the admin panel under "Device Profiles", and you will see a select box in the "Hashcat" session setup step. If a profile is deleted or disabled, the fallback will use all GPUs available (as it does now).

Don't forget to run the db migration for this, instructions at: https://github.com/ctxis/crackerjack/blob/master/docs/installation.md#update-to-latest-version (but checkout the `develop` instead of the `master` branch)

**Comment by tiahgar** [comment]
Heya, when you clone a fresh version of the develop branch and attemp to log in after creating an admin account, you get the following stack trace:
```
Traceback (most recent call last):
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/crackerjack/app/controllers/home.py", line 26, in index
    errors = healthcheck.run(provider)
  File "/tmp/crackerjack/app/lib/base/healthcheck.py", line 12, in run
    sessions = provider.sessions()
  File "/tmp/crackerjack/app/lib/base/provider.py", line 39, in sessions
    self.device_profiles()
  File "/tmp/crackerjack/app/lib/base/provider.py", line 148, in device_profiles
    return DeviceProfileManager(hashcat.get_detected_devices())
  File "/tmp/crackerjack/app/lib/hashcat/manager.py", line 518, in get_detected_devices
    output = self.shell.execute([self.hashcat_binary, '-I', '--force'], user_id=0, log_to_db=False)
  File "/tmp/crackerjack/app/lib/base/shell.py", line 21, in execute
    output = subprocess.run(command, stdout=subprocess.PIPE).stdout.decode().strip()
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
```
This is probably caused by the healthcheck assuming that the hashcat binary has been set, but it hasn't yet (the admin has to log on first and go to settings).

**Comment by sadreck** [comment]
Thanks for reporting it! I've just pushed a fix to the `develop` branch.

**Comment by sadreck** [comment]
I've pushed this to master, let me know if there are any issues with it. Thanks.

**Comment by tautology0** [comment]
Yep, it all looks good. Thanks!
