### ISSUE TITLE
Error when creating a new user

### ISSUE THREAD

**Issue by Chridolc** [ctxis/crackerjack#21]
Hello.
When trying to create a new user on the web interface (non admin, active), I have this error below. :

werkzeug.routing.BuildError: Could not build url for endpoint 'admin.user_edit' with values ['user_id']. Did you mean 'config.user_edit' instead?
Traceback (most recent call last)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view

    return func(*args, **kwargs)

    File "/opt/crackerjack/app/lib/base/decorators.py", line 13, in wrapped_view

    return f(**kwargs)

    File "/opt/crackerjack/app/controllers/config/system/users.py", line 48, in user_save

    return redirect(url_for('admin.user_edit', user_id=user_id))

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for

    return appctx.app.handle_url_build_error(error, endpoint, values)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error

    reraise(exc_type, exc_value, tb)

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for

    rv = url_adapter.build(

    File "/opt/crackerjack/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build

    raise BuildError(endpoint, values, method, self)

    werkzeug.routing.BuildError: Could not build url for endpoint 'admin.user_edit' with values ['user_id']. Did you mean 'config.user_edit' instead?

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Thanks for your help.

**Comment by sadreck** [comment]
Hi,

I'm using the latest and greatest and it's working fine - which version are you running?

Did you install CJ using git or did you download the zip/tar archive?

Thanks,
Pavel

**Comment by Chridolc** [comment]
Hello.

Sorry for the delay : CrackerJack v1.2.3 - Hashcat v6.2.5 , installed from Git, up to date.
actually running on a kali physical machine

**Comment by sadreck** [comment]
The plot thickens.

I think I know what it is, I've pushed the following update https://github.com/ctxis/crackerjack/commit/5df8c809820b9b55b7cf477a0175e84f4093bab9.

Can you follow the update process as described here please: https://github.com/ctxis/crackerjack/blob/master/docs/installation.md#update-to-latest-version - the main thing is to install the latest requirements.

If that doesn't work, can you do the following just to try to pinpoint if it's something in the repo or your local installation:

```
pavel@samaritan:~$ cd /tmp
pavel@samaritan:/tmp$ git clone https://github.com/ctxis/crackerjack.git
pavel@samaritan:/tmp$ cd crackerjack/
pavel@samaritan:/tmp/crackerjack$ python3.9 -m venv venv
pavel@samaritan:/tmp/crackerjack$ . venv/bin/activate
(venv) pavel@samaritan:/tmp/crackerjack$ pip install -r requirements.txt
(venv) pavel@samaritan:/tmp/crackerjack$ flask db init
(venv) pavel@samaritan:/tmp/crackerjack$ flask db migrate
(venv) pavel@samaritan:/tmp/crackerjack$ flask db upgrade
(venv) pavel@samaritan:/tmp/crackerjack$ export FLASK_ENV=development
(venv) pavel@samaritan:/tmp/crackerjack$ export FLASK_APP=app
(venv) pavel@samaritan:/tmp/crackerjack$ flask run
```

Then navigate to http://127.0.0.1:5000/ create your admin, and go and create your local user.

**Comment by sadreck** [comment]
I'll close this ticket, but if it's still an issue please open it again.
